version: '3.8'
services:

  # https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/
  traefik:
    image: "traefik:v2.10"
    hostname: studently.traefik
    container_name: studently.traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.apisecure.address=:444"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=simcice@edu.htl-villach.at"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

    ports:
      - "80:80"
      - "3000:3000"
      - "443:443"
      - "444:444"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - /var/run/docker.sock:/var/run/docker.sock


  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    hostname: studently.fastapi
    container_name: studently.fastapi
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`studently.fastapi`)"
      - "traefik.http.routers.fastapi.entrypoints=apisecure"
      - "traefik.http.routers.fastapi.tls.certresolver=myresolver"
    ports:
      - 8085:8085
    depends_on:
      - mongodb


  # astroweb:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   hostname: studently.astroweb
  #   container_name: studently.astroweb
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.fastapi.rule=Host(`studently.astroweb`)"
  #     - "traefik.http.routers.fastapi.entrypoints=websecure"
  #     - "traefik.http.routers.fastapi.tls.certresolver=myresolver"
  #   ports:
  #     - "4321:4312"
  #   depends_on:
  #     - mongodb
  #     - fastapi

  mongodb:
    image: mongo:latest
    hostname: studently.mongodb
    container_name: studently.mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: studently
      MONGO_INITDB_ROOT_PASSWORD: studently
    volumes:
      - mongodb_data:/data/db
      # - ./tls-ssl:/etc/mongodb-certs
    # command:
    #   - mongod
    #   - --tlsMode
    #   - requireTLS
    #   - --tlsCertificateKeyFile
    #   - /etc/mongodb-certs/key.pem
    #   - tlsCAFile
    #   - /etc/mongodb-certs/csr.pem



volumes:
  mongodb_data:
