version: '3.8'
services:
  
  mongodb:
    image: mongo:latest
    container_name: studentlymongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: studently
      MONGO_INITDB_ROOT_PASSWORD: studently
    volumes:
      - mongodb_data:/data/db


#   proxy:
#     build: ./
#     networks:
#       - studently_net
#     ports:
#       - 80:80
#       - 443:443

# networks:
#   studently_net:
#     external:
#       name: studently_net

volumes:
  mongodb_data:
