version: '3.8'
services:

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: studentlymongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: studently
      MONGO_INITDB_ROOT_PASSWORD: studently
    volumes:
      - mongodb_data:/data/db



volumes:
  mongodb_data:
