import { writable } from 'svelte/store';
import { get_profile } from "../api/services.ts"

const accessToken = "eyJ0eXAiOiJKV1QiLCJub25jZSI6IkFqOGtZTmNCVm5qdDNWbUdueV9fNC1LVHM4SjdDNTJxTDhKd2VFaE9qVUEiLCJhbGciOiJSUzI1NiIsIng1dCI6IlhSdmtvOFA3QTNVYVdTblU3Yk05blQwTWpoQSIsImtpZCI6IlhSdmtvOFA3QTNVYVdTblU3Yk05blQwTWpoQSJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8yYjE5N2VmYS04ZTFiLTQ2ODAtYjI2My04ZTIzNzg4OWI1YjMvIiwiaWF0IjoxNzExMDQyNzcxLCJuYmYiOjE3MTEwNDI3NzEsImV4cCI6MTcxMTEyOTQ3MSwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhXQUFBQTY5MjdLcXZxeS9FNDhNNlN0Y1VEcmVpM2RWWDlUdktybmlZdnhKV0RUYnpDdmQwamNkVnpmUUZHdWVJUC9UR1k5azczaTBNYkZNYXlJS2ttK3V4YjZBQTZBTjhuTzFudDE4dFRDQ0JOaVpnPSIsImFtciI6WyJwd2QiLCJyc2EiLCJtZmEiXSwiYXBwX2Rpc3BsYXluYW1lIjoiR3JhcGggRXhwbG9yZXIiLCJhcHBpZCI6ImRlOGJjOGI1LWQ5ZjktNDhiMS1hOGFkLWI3NDhkYTcyNTA2NCIsImFwcGlkYWNyIjoiMCIsImRldmljZWlkIjoiNWFiMjE1MTUtZDE4Yy00ZGM2LTgwMjYtOWE1MzhiZGIzZjczIiwiZmFtaWx5X25hbWUiOiJLVU5PUyIsImdpdmVuX25hbWUiOiJQYW5uYSIsImlkdHlwIjoidXNlciIsImlwYWRkciI6IjIxMy4xNjIuNzMuMTMxIiwibmFtZSI6IktVTk9TIFBhbm5hLCA1QUhJVFMiLCJvaWQiOiI4MjhkYzE1OC00NzY1LTQ0ZjItOTA4OC02ZWFiNjdmZmEyYzciLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtNzc0OTE2MTIxLTc4NzMyODgwNi05MTE4MzEwMzYtMjM4NDEiLCJwbGF0ZiI6IjMiLCJwdWlkIjoiMTAwMzIwMDA2QzI5NDJENSIsInJoIjoiMC5BUkFBLW40Wkt4dU9nRWF5WTQ0amVJbTFzd01BQUFBQUFBQUF3QUFBQUFBQUFBQ1hBT0EuIiwic2NwIjoiRGlyZWN0b3J5LkFjY2Vzc0FzVXNlci5BbGwgRGlyZWN0b3J5LlJlYWQuQWxsIERpcmVjdG9yeS5SZWFkV3JpdGUuQWxsIEVkdUFzc2lnbm1lbnRzLlJlYWRXcml0ZSBHcm91cC5SZWFkLkFsbCBHcm91cC5SZWFkV3JpdGUuQWxsIG9wZW5pZCBwcm9maWxlIFVzZXIuUmVhZCBlbWFpbCIsInNpZ25pbl9zdGF0ZSI6WyJrbXNpIl0sInN1YiI6IjZyN2xxNGlPZ0ZxdmI3MGFuYnhSZmswZFNpbkFGYTMtZndBb1RIV1ZJVnciLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiRVUiLCJ0aWQiOiIyYjE5N2VmYS04ZTFiLTQ2ODAtYjI2My04ZTIzNzg4OWI1YjMiLCJ1bmlxdWVfbmFtZSI6Imt1bm9zcEBlZHUuaHRsLXZpbGxhY2guYXQiLCJ1cG4iOiJrdW5vc3BAZWR1Lmh0bC12aWxsYWNoLmF0IiwidXRpIjoiOXJxc0ozWDVrazZZQ3JWSGYtOWdBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19jYyI6WyJDUDEiXSwieG1zX3NzbSI6IjEiLCJ4bXNfc3QiOnsic3ViIjoieU9teHlNQWZtOUpxWmxXR0M4NzZtMDJGd09sZGlsbmVxN0poRG8zQXU1VSJ9LCJ4bXNfdGNkdCI6MTM1NDAxMDI2NiwieG1zX3RkYnIiOiJFVSJ9.IEC-PrDDU31IOEH86kOA6pyKZjIgf7Y3MWUz-nMSBPcVkHp7IUORzUsSVQ7peCUewSbWKZIQROYY1kSOVsXkPY5YMIgNwO8NaXVeYS74-62L8HaHIYd7kbxZO7ijMHaIYKzTfBNnDQBe5MMXCRhaVRBkgAUDSrBUKUugCqdkPnMMSbw_MTSKwnfF9FdzrpA2ErnGj-teWKaPB9UIq-3Ip2NFgE6eOPnlN6D5uAD4vMONQbNwhK0JwLh43txFZqtwGJQUNp4lUDYSiTPBk_cc5qxThdUsniTjM7VPTaPmve6dZHRyaTd3kbh4nXeg47-sMroPfOQ4iyH0rLM5vmJIJw";

let profile = await get_profile(accessToken);
profile = profile.message.profile;

export const user = writable({
    disabled: profile.disabled,
    identifier: profile.identifier,
    username: profile.username,
    firstname: profile.firstname,
    lastname: profile.lastname,
    email: profile.email,
    expires: profile.expires,
    created: profile.created,
    sclass: profile.sclass,
    type: profile.type,
    owned_objects: profile.owned_objects,
    owned_payments: profile.owned_payments,
});